# Global App Settings
app:
  name: "RecommendationHaki"
  version: "2.0.0"
  debug: false
  random_seed: 42

# Data Ingestion
api:
  jikan_base_url: "https://api.jikan.moe/v4"
  batch_size: 25
  delay_seconds: 1.0
  max_retries: 3
  
  # Total Anime Scraped = batch_size * max_pages
  # Example: 25 items/page * 100 pages = 2500 records
  max_pages: 100

# File Paths (Relative to project root)
paths:
  raw_data: "data/raw/anime_master_db.csv"
  processed_data: "data/processed/cleaned_anime_data.csv"

  # Artifacts
  vectorizer: "artifacts/vectorizer.joblib"
  vector_embeddings: "artifacts/vector_embeddings.pkl"
  knn_model: "artifacts/knn_model.joblib"

  # Static Assets
  logo: "app/assets/logo.png"
  css: "app/assets/styles.css"
  favicon: "app/assets/favicon.png"

# Model Hyperparameters
model:
  top_k_recommendations: 4
  vectorizer_max_features: 5000

# Project Contributors
contributors:
  - name: "Asif Sayyed"
    github: "https://github.com/Asifdotexe"
    image: "https://avatars.githubusercontent.com/u/115421661?v=4"
  - name: "Pranjal Dhamane"
    github: "https://github.com/PranjalDhamane"
    image: "https://avatars.githubusercontent.com/u/131870182?v=4"
  - name: "Tanvi Sivaraj"
    github: "https://github.com/tanvisivaraj"
    image: "https://avatars.githubusercontent.com/u/132070958?v=4"
  - name: "Shrawani Thakur"
    github: "https://github.com/str04"
    image: "https://avatars.githubusercontent.com/u/123924840?v=4"
  - name: "Aditi Mane"
    github: "https://github.com/aditimane07"
    image: "https://avatars.githubusercontent.com/u/129670339?v=4"
