app:
  title: "AniMate"
  page_title: "AniMate"
  loading_phrases:
    - "ğŸ” Searching for hidden gems in the anime universe..."
    - "âœ¨ Summoning the perfect anime recommendations..."
    - "ğŸ‰ Gathering the coolest anime just for you..."
    - "ğŸ“š Digging through the anime archives for you..."
    - "ğŸš€ Launching into the world of anime to find your match..."
    - "ğŸŒŸ Fetching the ultimate anime experience..."
    - "ğŸŒ€ Sifting through dimensions for the best recommendations..."
    - "ğŸ’« Scouring the anime cosmos for your next favorite..."

data:
  file_path: "data/final/AnimeData_25092024.csv"
  dtypes:
    title: "category"
    other_name: "category"
    genres: "category"
    synopsis: "string"
    studio: "category"
    demographic: "category"
    source: "category"
    duration_category: "category"
    total_duration_hours: "float32"
    score: "float32"
    image_url: "string"

model:
  max_features: 5000
  n_neighbors: 5
  metric: "cosine"
  default_top_n: 5

contributors:
  - name: "Asif Sayyed"
    github: "https://github.com/Asifdotexe"
    image: "https://avatars.githubusercontent.com/u/115421661?v=4"
  - name: "Pranjal Dhamane"
    github: "https://github.com/PranjalDhamane"
    image: "https://avatars.githubusercontent.com/u/131870182?v=4"
  - name: "Tanvi Sivaraj"
    github: "https://github.com/tanvisivaraj"
    image: "https://avatars.githubusercontent.com/u/132070958?v=4"
  - name: "Shrawani Thakur"
    github: "https://github.com/str04"
    image: "https://avatars.githubusercontent.com/u/123924840?v=4"
  - name: "Aditi Mane"
    github: "https://github.com/aditimane07"
    image: "https://avatars.githubusercontent.com/u/129670339?v=4"
